config/routes.rb
Rails.application.routes.draw do
  resources :continents
  resources :arts
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
	belongs_to :continent
end

app/models/continent.rb
class Continent < ApplicationRecord
	has_many :arts
	def to_s
		"#{title}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]

  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      params.require(:art).permit(:title, :date, :image, :description, :continent_id)
    end
end

app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
  before_action :set_continent, only: [:show, :edit, :update, :destroy]

  # GET /continents
  # GET /continents.json
  def index
    @continents = Continent.all
  end

  # GET /continents/1
  # GET /continents/1.json
  def show
  end

  # GET /continents/new
  def new
    @continent = Continent.new
  end

  # GET /continents/1/edit
  def edit
  end

  # POST /continents
  # POST /continents.json
  def create
    @continent = Continent.new(continent_params)

    respond_to do |format|
      if @continent.save
        format.html { redirect_to @continent, notice: 'Continent was successfully created.' }
        format.json { render :show, status: :created, location: @continent }
      else
        format.html { render :new }
        format.json { render json: @continent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /continents/1
  # PATCH/PUT /continents/1.json
  def update
    respond_to do |format|
      if @continent.update(continent_params)
        format.html { redirect_to @continent, notice: 'Continent was successfully updated.' }
        format.json { render :show, status: :ok, location: @continent }
      else
        format.html { render :edit }
        format.json { render json: @continent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /continents/1
  # DELETE /continents/1.json
  def destroy
    @continent.destroy
    respond_to do |format|
      format.html { redirect_to continents_url, notice: 'Continent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_continent
      @continent = Continent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def continent_params
      params.require(:continent).permit(:title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/views/arts/_form.html.erb
<%= form_with(model: art, local: true) do |form| %>
  <% if art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.select :continent_id, Continent.all.map {|continent| [continent.title, continent.id]}%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing Art</h1>

<%= render 'form', art: @art %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
  <center>
    <br>
    <br>
    <blockquote class="blockquote text-center">
  <h2 class="mb-0">La femme naît libre et demeure égale à l'homme en droits.</h2>
  <footer class="blockquote-footer">Olympes de Gouges</footer>
</blockquote>
  
<div class="row">
    <% @arts.each do |art| %>
      <div class="col-md-3">
        <h3>
        <%= image_tag art.image, class: 'img-fluid' %>
        <td><%= art.title %></td>
        </h3>
        <h4>
        <td><%= art.date %></td>
        </h4>
        <td><%= simple_format art.description%></td>
        <td class="btn btn-default"><%= link_to 'Afficher', art %></td>
        <td class="btn btn-default"><%= link_to 'Editer', edit_art_path(art) %></td>
        <td class="btn btn-default"><%= link_to 'Supprimer', art, method: :delete, data: { confirm: 'Êtes vous certain ?' } %></td>
      </div>
    <% end %>
</div>

<%= link_to 'New Art', new_art_path %>

app/views/arts/new.html.erb
<h1>New Art</h1>

<%= render 'form', art: @art %>

<%= link_to 'Back', arts_path %>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>

<h4>
  <strong>Titre:</strong>
  <%= link_to @art.title %> 
</h4>

<h4>
  <strong>Date:</strong>
  <%= @art.date %>
</h4>

<h4>
  <strong>Oeuvre:</strong>
  <br>
  <%= image_tag @art.image %>
</h4>

<h4>
  <strong>Description:</strong>
  <%= @art.description %>
</h4>

<h4 >
<strong>conti</strong>
<%= link_to @art.continent, @art.continent %>
</h4>

<%= link_to 'Editer', edit_art_path(@art) %> |
<%= link_to 'Retour', arts_path %>

app/views/continents/_form.html.erb
<%= form_with(model: continent, local: true) do |form| %>
  <% if continent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(continent.errors.count, "error") %> prohibited this continent from being saved:</h2>

      <ul>
      <% continent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/continents/edit.html.erb
<h1>Editing Continent</h1>

<%= render 'form', continent: @continent %>

<%= link_to 'Show', @continent %> |
<%= link_to 'Back', continents_path %>

app/views/continents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Continents</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @continents.each do |continent| %>
    <% link_to continent %>
      <tr>
        <td><%= continent.title %></td>
        <td><%= link_to 'Show', continent %></td>
        <td><%= link_to 'Edit', edit_continent_path(continent) %></td>
        <td><%= link_to 'Destroy', continent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Continent', new_continent_path %>

app/views/continents/new.html.erb
<h1>New Continent</h1>

<%= render 'form', continent: @continent %>

<%= link_to 'Back', continents_path %>

app/views/continents/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>
<%= @continent.title %> 
</h1>

<div class="row">
    <% @continent.arts.each do |art| %>
		<div class="col-md-3">
			<%= image_tag art.image, class: 'img-fluid' %>
		</div>
	<% end %>
</div>

<%= link_to 'Edit', edit_continent_path(@continent) %> |
<%= link_to 'Back', continents_path %>

app/views/home/index.html.erb
<center>
	<br>
	<br>
	<h1>
Bienvenue<BR>
</h1>
<h2> Parce que le 8 mars est nôtre journée : Joyeux anniversaire !<h2>
<br>
<br>
	<img src="https://larotative.info/home/chroot_ml/ml-tours/ml-tours/public_html/local/cache-vignettes/L700xH366/arton2987-00057-ab98c.jpg?1544257842"
	alt="Home">
	<img src="http://quartierlibre.ca/wp-content/uploads/2014/11/feminisme_p19_LydiaKepinski.jpg"
	alt= "Go on !"
	height= "400px"
	width="400px">
   

app/views/layouts/_navigation.html.erb
<header>

	<%=link_to 'Home', root_path %>
	<br>
	<br>
	<nav>
		<%=link_to 'Say hello to feminism', arts_path %>

	</nav>
	<nav>
		<% Continent.all.each do |continent| %>
			<%= link_to continent, continent %>

		<% end %>
	</nav>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ô femmes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <div class="container"> 
      <%= render 'layouts/navigation' %>
      <%= yield %>
    </div>
  </body>
</html>